[{code="AF",nom="Afghanistan"},
{code="ZA",nom="Afrique du Sud"},
{code="AL",nom="Albanie"},
{code="DZ",nom="Algérie"},
{code="DE",nom="Allemagne"},
{code="AD",nom="Andorre"},
{code="AO",nom="Angola"},
{code="AI",nom="Anguilla"},
{code="AQ",nom="Antarctique"},
{code="AG",nom="Antigua-et-Barbuda"},
{code="AN",nom="Antilles néerlandaises"},
{code="SA",nom="Arabie saoudite"},
{code="AR",nom="Argentine"},
{code="AM",nom="Arménie"},
{code="AW",nom="Aruba"},
{code="AU",nom="Australie"},
{code="AT",nom="Autriche"},
{code="AZ",nom="Azerbaïdjan"},
{code="BJ",nom="Bénin"},
{code="BS",nom="Bahamas"},
{code="BH",nom="Bahreïn"},
{code="BD",nom="Bangladesh"},
{code="BB",nom="Barbade"},
{code="PW",nom="Belau"},
{code="BE",nom="Belgique"},
{code="BZ",nom="Belize"},
{code="BM",nom="Bermudes"},
{code="BT",nom="Bhoutan"},
{code="BY",nom="Biélorussie"},
{code="MM",nom="Birmanie"},
{code="BO",nom="Bolivie"},
{code="BA",nom="Bosnie-Herzégovine"},
{code="BW",nom="Botswana"},
{code="BR",nom="Brésil"},
{code="BN",nom="Brunei"},
{code="BG",nom="Bulgarie"},
{code="BF",nom="Burkina Faso"},
{code="BI",nom="Burundi"},
{code="CI",nom="Côte d'Ivoire"},
{code="KH",nom="Cambodge"},
{code="CM",nom="Cameroun"},
{code="CA",nom="Canada"},
{code="CV",nom="Cap-Vert"},
{code="CL",nom="Chili"},
{code="CN",nom="Chine"},
{code="CY",nom="Chypre"},
{code="CO",nom="Colombie"},
{code="KM",nom="Comores"},
{code="CG",nom="Congo"},
{code="KP",nom="Corée du Nord"},
{code="KR",nom="Corée du Sud"},
{code="CR",nom="Costa Rica"},
{code="HR",nom="Croatie"},
{code="CU",nom="Cuba"},
{code="DK",nom="Danemark"},
{code="DJ",nom="Djibouti"},
{code="DM",nom="Dominique"},
{code="EG",nom="Égypte"},
{code="AE",nom="Émirats arabes unis"},
{code="EC",nom="Équateur"},
{code="ER",nom="Érythrée"},
{code="ES",nom="Espagne"},
{code="EE",nom="Estonie"},
{code="US",nom="États-Unis"},
{code="ET",nom="Éthiopie"},
{code="FI",nom="Finlande"},
{code="FR",nom="France"},
{code="GE",nom="Géorgie"},
{code="GA",nom="Gabon"},
{code="GM",nom="Gambie"},
{code="GH",nom="Ghana"},
{code="GI",nom="Gibraltar"},
{code="GR",nom="Grèce"},
{code="GD",nom="Grenade"},
{code="GL",nom="Groenland"},
{code="GP",nom="Guadeloupe"},
{code="GU",nom="Guam"},
{code="GT",nom="Guatemala"},
{code="GN",nom="Guinée"},
{code="GQ",nom="Guinée équatoriale"},
{code="GW",nom="Guinée-Bissao"},
{code="GY",nom="Guyana"},
{code="GF",nom="Guyane fran‡aise"},
{code="HT",nom="Haïti"},
{code="HN",nom="Honduras"},
{code="HK",nom="Hong Kong"},
{code="HU",nom="Hongrie"},
{code="BV",nom="Ile Bouvet"},
{code="CX",nom="Ile Christmas"},
{code="NF",nom="Ile Norfolk"},
{code="KY",nom="Iles Cayman"},
{code="CK",nom="Iles Cook"},
{code="FO",nom="Iles Féroé"},
{code="FK",nom="Iles Falkland"},
{code="FJ",nom="Iles Fidji"},
{code="GS",nom="Iles Géorgie du Sud et Sandwich du Sud"},
{code="HM",nom="Iles Heard et McDonald"},
{code="MH",nom="Iles Marshall"},
{code="PN",nom="Iles Pitcairn"},
{code="SB",nom="Iles Salomon"},
{code="SJ",nom="Iles Svalbard et Jan Mayen"},
{code="TC",nom="Iles Turks-et-Caicos"},
{code="VI",nom="Iles Vierges américaines"},
{code="VG",nom="Iles Vierges britanniques"},
{code="CC",nom="Iles des Cocos (Keeling)"},
{code="UM",nom="Iles mineures éloignées des tats-Unis"},
{code="IN",nom="Inde"},
{code="ID",nom="Indonésie"},
{code="IR",nom="Iran"},
{code="IQ",nom="Iraq"},
{code="IE",nom="Irlande"},
{code="IS",nom="Islande"},
{code="IL",nom="Isra‰l"},
{code="IT",nom="Italie"},
{code="JM",nom="Jamaïque"},
{code="JP",nom="Japon"},
{code="JO",nom="Jordanie"},
{code="KZ",nom="Kazakhstan"},
{code="KE",nom="Kenya"},
{code="KG",nom="Kirghizistan"},
{code="KI",nom="Kiribati"},
{code="KW",nom="Koweït"},
{code="LA",nom="Laos"},
{code="LS",nom="Lesotho"},
{code="LV",nom="Lettonie"},
{code="LB",nom="Liban"},
{code="LR",nom="Liberia"},
{code="LY",nom="Libye"},
{code="LI",nom="Liechtenstein"},
{code="LT",nom="Lituanie"},
{code="LU",nom="Luxembourg"},
{code="MO",nom="Macao"},
{code="MG",nom="Madagascar"},
{code="MY",nom="Malaisie"},
{code="MW",nom="Malawi"},
{code="MV",nom="Maldives"},
{code="ML",nom="Mali"},
{code="MT",nom="Malte"},
{code="MP",nom="Mariannes du Nord"},
{code="MA",nom="Maroc"},
{code="MQ",nom="Martinique"},
{code="MU",nom="Maurice"},
{code="MR",nom="Mauritanie"},
{code="YT",nom="Mayotte"},
{code="MX",nom="Mexique"},
{code="FM",nom="Micronésie"},
{code="MD",nom="Moldavie"},
{code="MC",nom="Monaco"},
{code="MN",nom="Mongolie"},
{code="MS",nom="Montserrat"},
{code="MZ",nom="Mozambique"},
{code="NP",nom="Népal"},
{code="NA",nom="Namibie"},
{code="NR",nom="Nauru"},
{code="NI",nom="Nicaragua"},
{code="NE",nom="Niger"},
{code="NG",nom="Nigeria"},
{code="NU",nom="Nioué"},
{code="NO",nom="Norvège"},
{code="NC",nom="Nouvelle-Calédonie"},
{code="NZ",nom="Nouvelle-Zélande"},
{code="OM",nom="Oman"},
{code="UG",nom="Ouganda"},
{code="UZ",nom="Ouzbékistan"},
{code="PE",nom="Pérou"},
{code="PK",nom="Pakistan"},
{code="PA",nom="Panama"},
{code="PG",nom="Papouasie-Nouvelle-Guinée"},
{code="PY",nom="Paraguay"},
{code="NL",nom="Pays-Bas"},
{code="PH",nom="Philippines"},
{code="PL",nom="Pologne"},
{code="PF",nom="Polynésie fran‡aise"},
{code="PR",nom="Porto Rico"},
{code="PT",nom="Portugal"},
{code="QA",nom="Qatar"},
{code="CF",nom="République centrafricaine"},
{code="CD",nom="République démocratique du Congo"},
{code="DO",nom="République dominicaine"},
{code="CZ",nom="République tchèque"},
{code="RE",nom="Réunion"},
{code="RO",nom="Roumanie"},
{code="GB",nom="Royaume-Uni"},
{code="RU",nom="Russie"},
{code="RW",nom="Rwanda"},
{code="SN",nom="Sénégal"},
{code="EH",nom="Sahara occidental"},
{code="KN",nom="Saint-Christophe-et-Niévès"},
{code="SM",nom="Saint-Marin"},
{code="PM",nom="Saint-Pierre-et-Miquelon"},
{code="VA",nom="Saint-Siège"},
{code="VC",nom="Saint-Vincent-et-les-Grenadines"},
{code="SH",nom="Sainte-Hélène"},
{code="LC",nom="Sainte-Lucie"},
{code="SV",nom="Salvador"},
{code="WS",nom="Samoa"},
{code="AS",nom="Samoa américaines"},
{code="ST",nom="Sao Tomé-et-Principe"},
{code="SC",nom="Seychelles"},
{code="SL",nom="Sierra Leone"},
{code="SG",nom="Singapour"},
{code="SI",nom="Slovénie"},
{code="SK",nom="Slovaquie"},
{code="SO",nom="Somalie"},
{code="SD",nom="Soudan"},
{code="LK",nom="Sri Lanka"},
{code="SE",nom="Suède"},
{code="CH",nom="Suisse"},
{code="SR",nom="Suriname"},
{code="SZ",nom="Swaziland"},
{code="SY",nom="Syrie"},
{code="TW",nom="Taïwan"},
{code="TJ",nom="Tadjikistan"},
{code="TZ",nom="Tanzanie"},
{code="TD",nom="Tchad"},
{code="TF",nom="Terres australes fran‡aises"},
{code="IO",nom="Territoire britannique de l'Océan Indien"},
{code="TH",nom="Thaïlande"},
{code="TL",nom="Timor Oriental"},
{code="TG",nom="Togo"},
{code="TK",nom="Tokélaou"},
{code="TO",nom="Tonga"},
{code="TT",nom="Trinité-et-Tobago"},
{code="TN",nom="Tunisie"},
{code="TM",nom="Turkménistan"},
{code="TR",nom="Turquie"},
{code="TV",nom="Tuvalu"},
{code="UA",nom="Ukraine"},
{code="UY",nom="Uruguay"},
{code="VU",nom="Vanuatu"},
{code="VE",nom="Venezuela"},
{code="VN",nom="Viêt Nam"},
{code="WF",nom="Wallis-et-Futuna"},
{code="YE",nom="Yémen"},
{code="YU",nom="Yougoslavie"},
{code="ZM",nom="Zambie"},
{code="ZW",nom="Zimbabwe"}]